// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: egp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryType int32

const (
	CategoryType_CATEGORY_TYPE_NONE          CategoryType = 0
	CategoryType_CATEGORY_TYPE_EBISU_1       CategoryType = 1
	CategoryType_CATEGORY_TYPE_EBISU_2       CategoryType = 2
	CategoryType_CATEGORY_TYPE_EBISU_WEST    CategoryType = 3
	CategoryType_CATEGORY_TYPE_EBISU_SOUTH   CategoryType = 4
	CategoryType_CATEGORY_TYPE_BEER_COCKTAIL CategoryType = 5
)

// Enum value maps for CategoryType.
var (
	CategoryType_name = map[int32]string{
		0: "CATEGORY_TYPE_NONE",
		1: "CATEGORY_TYPE_EBISU_1",
		2: "CATEGORY_TYPE_EBISU_2",
		3: "CATEGORY_TYPE_EBISU_WEST",
		4: "CATEGORY_TYPE_EBISU_SOUTH",
		5: "CATEGORY_TYPE_BEER_COCKTAIL",
	}
	CategoryType_value = map[string]int32{
		"CATEGORY_TYPE_NONE":          0,
		"CATEGORY_TYPE_EBISU_1":       1,
		"CATEGORY_TYPE_EBISU_2":       2,
		"CATEGORY_TYPE_EBISU_WEST":    3,
		"CATEGORY_TYPE_EBISU_SOUTH":   4,
		"CATEGORY_TYPE_BEER_COCKTAIL": 5,
	}
)

func (x CategoryType) Enum() *CategoryType {
	p := new(CategoryType)
	*p = x
	return p
}

func (x CategoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CategoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_egp_proto_enumTypes[0].Descriptor()
}

func (CategoryType) Type() protoreflect.EnumType {
	return &file_egp_proto_enumTypes[0]
}

func (x CategoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CategoryType.Descriptor instead.
func (CategoryType) EnumDescriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{0}
}

type SearchType int32

const (
	SearchType_SEARCH_TYPE_IN_CURRENT_SALES  SearchType = 0
	SearchType_SEARCH_TYPE_NOT_YET           SearchType = 1
	SearchType_SEARCH_TYPE_IRREGULAR_HOLIDAY SearchType = 2
	SearchType_SEARCH_TYPE_NEEDS_RESERVATION SearchType = 3
	SearchType_SEARCH_TYPE_BEER_COCKTAIL     SearchType = 4
)

// Enum value maps for SearchType.
var (
	SearchType_name = map[int32]string{
		0: "SEARCH_TYPE_IN_CURRENT_SALES",
		1: "SEARCH_TYPE_NOT_YET",
		2: "SEARCH_TYPE_IRREGULAR_HOLIDAY",
		3: "SEARCH_TYPE_NEEDS_RESERVATION",
		4: "SEARCH_TYPE_BEER_COCKTAIL",
	}
	SearchType_value = map[string]int32{
		"SEARCH_TYPE_IN_CURRENT_SALES":  0,
		"SEARCH_TYPE_NOT_YET":           1,
		"SEARCH_TYPE_IRREGULAR_HOLIDAY": 2,
		"SEARCH_TYPE_NEEDS_RESERVATION": 3,
		"SEARCH_TYPE_BEER_COCKTAIL":     4,
	}
)

func (x SearchType) Enum() *SearchType {
	p := new(SearchType)
	*p = x
	return p
}

func (x SearchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchType) Descriptor() protoreflect.EnumDescriptor {
	return file_egp_proto_enumTypes[1].Descriptor()
}

func (SearchType) Type() protoreflect.EnumType {
	return &file_egp_proto_enumTypes[1]
}

func (x SearchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchType.Descriptor instead.
func (SearchType) EnumDescriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{1}
}

type SortOrderType int32

const (
	SortOrderType_SORT_ORDER_NO       SortOrderType = 0
	SortOrderType_SORT_ORDER_DISTANCE SortOrderType = 1
)

// Enum value maps for SortOrderType.
var (
	SortOrderType_name = map[int32]string{
		0: "SORT_ORDER_NO",
		1: "SORT_ORDER_DISTANCE",
	}
	SortOrderType_value = map[string]int32{
		"SORT_ORDER_NO":       0,
		"SORT_ORDER_DISTANCE": 1,
	}
)

func (x SortOrderType) Enum() *SortOrderType {
	p := new(SortOrderType)
	*p = x
	return p
}

func (x SortOrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_egp_proto_enumTypes[2].Descriptor()
}

func (SortOrderType) Type() protoreflect.EnumType {
	return &file_egp_proto_enumTypes[2]
}

func (x SortOrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrderType.Descriptor instead.
func (SortOrderType) EnumDescriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{2}
}

type YearOrder int32

const (
	YearOrder_YEAR_ORDER_ASC  YearOrder = 0
	YearOrder_YEAR_ORDER_DESC YearOrder = 1
)

// Enum value maps for YearOrder.
var (
	YearOrder_name = map[int32]string{
		0: "YEAR_ORDER_ASC",
		1: "YEAR_ORDER_DESC",
	}
	YearOrder_value = map[string]int32{
		"YEAR_ORDER_ASC":  0,
		"YEAR_ORDER_DESC": 1,
	}
)

func (x YearOrder) Enum() *YearOrder {
	p := new(YearOrder)
	*p = x
	return p
}

func (x YearOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (YearOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_egp_proto_enumTypes[3].Descriptor()
}

func (YearOrder) Type() protoreflect.EnumType {
	return &file_egp_proto_enumTypes[3]
}

func (x YearOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use YearOrder.Descriptor instead.
func (YearOrder) EnumDescriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{3}
}

type Date struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day           int32                  `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Date) Reset() {
	*x = Date{}
	mi := &file_egp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{0}
}

func (x *Date) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Date) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *Date) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	StartDate     *Date                  `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *Date                  `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_egp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Event) GetStartDate() *Date {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Event) GetEndDate() *Date {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_egp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{2}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Categories struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Categories) Reset() {
	*x = Categories{}
	mi := &file_egp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Categories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Categories) ProtoMessage() {}

func (x *Categories) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Categories.ProtoReflect.Descriptor instead.
func (*Categories) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{3}
}

func (x *Categories) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type BeerType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeerType) Reset() {
	*x = BeerType{}
	mi := &file_egp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeerType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeerType) ProtoMessage() {}

func (x *BeerType) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeerType.ProtoReflect.Descriptor instead.
func (*BeerType) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{4}
}

func (x *BeerType) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BeerType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BeerTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BeerTypes     []*BeerType            `protobuf:"bytes,1,rep,name=beer_types,json=beerTypes,proto3" json:"beer_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeerTypes) Reset() {
	*x = BeerTypes{}
	mi := &file_egp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeerTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeerTypes) ProtoMessage() {}

func (x *BeerTypes) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeerTypes.ProtoReflect.Descriptor instead.
func (*BeerTypes) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{5}
}

func (x *BeerTypes) GetBeerTypes() []*BeerType {
	if x != nil {
		return x.BeerTypes
	}
	return nil
}

type Shop struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId                    int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Year                       int32                  `protobuf:"varint,34,opt,name=year,proto3" json:"year,omitempty"`
	CategoryId                 CategoryType           `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3,enum=egp.CategoryType" json:"category_id,omitempty"`
	CategoryName               string                 `protobuf:"bytes,35,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	No                         int32                  `protobuf:"varint,4,opt,name=no,proto3" json:"no,omitempty"`
	ShopName                   string                 `protobuf:"bytes,5,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	MenuName                   string                 `protobuf:"bytes,6,opt,name=menu_name,json=menuName,proto3" json:"menu_name,omitempty"`
	MenuImageUrl               string                 `protobuf:"bytes,36,opt,name=menu_image_url,json=menuImageUrl,proto3" json:"menu_image_url,omitempty"`
	Phone                      string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Address                    string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	BusinessDays               string                 `protobuf:"bytes,9,opt,name=business_days,json=businessDays,proto3" json:"business_days,omitempty"`
	RegularHoliday             string                 `protobuf:"bytes,10,opt,name=regular_holiday,json=regularHoliday,proto3" json:"regular_holiday,omitempty"`
	BusinessHours              string                 `protobuf:"bytes,11,opt,name=business_hours,json=businessHours,proto3" json:"business_hours,omitempty"`
	ChargePrice                string                 `protobuf:"bytes,12,opt,name=charge_price,json=chargePrice,proto3" json:"charge_price,omitempty"`
	NormalizedChargePrice      int32                  `protobuf:"varint,13,opt,name=normalized_charge_price,json=normalizedChargePrice,proto3" json:"normalized_charge_price,omitempty"`
	SinglePrice                string                 `protobuf:"bytes,14,opt,name=single_price,json=singlePrice,proto3" json:"single_price,omitempty"`
	NormalizedSinglePrice      int32                  `protobuf:"varint,15,opt,name=normalized_single_price,json=normalizedSinglePrice,proto3" json:"normalized_single_price,omitempty"`
	SetPrice                   string                 `protobuf:"bytes,16,opt,name=set_price,json=setPrice,proto3" json:"set_price,omitempty"`
	NormalizedSetPrice         int32                  `protobuf:"varint,17,opt,name=normalized_set_price,json=normalizedSetPrice,proto3" json:"normalized_set_price,omitempty"`
	BeerType                   string                 `protobuf:"bytes,18,opt,name=beer_type,json=beerType,proto3" json:"beer_type,omitempty"`
	NeedsReservation           string                 `protobuf:"bytes,19,opt,name=needs_reservation,json=needsReservation,proto3" json:"needs_reservation,omitempty"`
	NormalizedNeedsReservation bool                   `protobuf:"varint,20,opt,name=normalized_needs_reservation,json=normalizedNeedsReservation,proto3" json:"normalized_needs_reservation,omitempty"`
	UseHachipay                string                 `protobuf:"bytes,21,opt,name=use_hachipay,json=useHachipay,proto3" json:"use_hachipay,omitempty"`
	NormalizedUseHachipay      bool                   `protobuf:"varint,22,opt,name=normalized_use_hachipay,json=normalizedUseHachipay,proto3" json:"normalized_use_hachipay,omitempty"`
	IsOpenHoliday              bool                   `protobuf:"varint,23,opt,name=is_open_holiday,json=isOpenHoliday,proto3" json:"is_open_holiday,omitempty"`
	IsIrregularHoliday         bool                   `protobuf:"varint,24,opt,name=is_irregular_holiday,json=isIrregularHoliday,proto3" json:"is_irregular_holiday,omitempty"`
	Latitude                   float64                `protobuf:"fixed64,25,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude                  float64                `protobuf:"fixed64,26,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Distance                   string                 `protobuf:"bytes,27,opt,name=distance,proto3" json:"distance,omitempty"`
	WeekNumber                 int32                  `protobuf:"varint,28,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	DayOfWeek                  int32                  `protobuf:"varint,29,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	StartTime                  string                 `protobuf:"bytes,30,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime                    string                 `protobuf:"bytes,31,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsHoliday                  bool                   `protobuf:"varint,32,opt,name=is_holiday,json=isHoliday,proto3" json:"is_holiday,omitempty"`
	InCurrentSales             bool                   `protobuf:"varint,33,opt,name=in_current_sales,json=inCurrentSales,proto3" json:"in_current_sales,omitempty"`
	IsStamped                  bool                   `protobuf:"varint,37,opt,name=is_stamped,json=isStamped,proto3" json:"is_stamped,omitempty"`
	NumberOfTimes              int32                  `protobuf:"varint,38,opt,name=number_of_times,json=numberOfTimes,proto3" json:"number_of_times,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Shop) Reset() {
	*x = Shop{}
	mi := &file_egp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shop) ProtoMessage() {}

func (x *Shop) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shop.ProtoReflect.Descriptor instead.
func (*Shop) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{6}
}

func (x *Shop) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Shop) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Shop) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Shop) GetCategoryId() CategoryType {
	if x != nil {
		return x.CategoryId
	}
	return CategoryType_CATEGORY_TYPE_NONE
}

func (x *Shop) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Shop) GetNo() int32 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *Shop) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *Shop) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *Shop) GetMenuImageUrl() string {
	if x != nil {
		return x.MenuImageUrl
	}
	return ""
}

func (x *Shop) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Shop) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Shop) GetBusinessDays() string {
	if x != nil {
		return x.BusinessDays
	}
	return ""
}

func (x *Shop) GetRegularHoliday() string {
	if x != nil {
		return x.RegularHoliday
	}
	return ""
}

func (x *Shop) GetBusinessHours() string {
	if x != nil {
		return x.BusinessHours
	}
	return ""
}

func (x *Shop) GetChargePrice() string {
	if x != nil {
		return x.ChargePrice
	}
	return ""
}

func (x *Shop) GetNormalizedChargePrice() int32 {
	if x != nil {
		return x.NormalizedChargePrice
	}
	return 0
}

func (x *Shop) GetSinglePrice() string {
	if x != nil {
		return x.SinglePrice
	}
	return ""
}

func (x *Shop) GetNormalizedSinglePrice() int32 {
	if x != nil {
		return x.NormalizedSinglePrice
	}
	return 0
}

func (x *Shop) GetSetPrice() string {
	if x != nil {
		return x.SetPrice
	}
	return ""
}

func (x *Shop) GetNormalizedSetPrice() int32 {
	if x != nil {
		return x.NormalizedSetPrice
	}
	return 0
}

func (x *Shop) GetBeerType() string {
	if x != nil {
		return x.BeerType
	}
	return ""
}

func (x *Shop) GetNeedsReservation() string {
	if x != nil {
		return x.NeedsReservation
	}
	return ""
}

func (x *Shop) GetNormalizedNeedsReservation() bool {
	if x != nil {
		return x.NormalizedNeedsReservation
	}
	return false
}

func (x *Shop) GetUseHachipay() string {
	if x != nil {
		return x.UseHachipay
	}
	return ""
}

func (x *Shop) GetNormalizedUseHachipay() bool {
	if x != nil {
		return x.NormalizedUseHachipay
	}
	return false
}

func (x *Shop) GetIsOpenHoliday() bool {
	if x != nil {
		return x.IsOpenHoliday
	}
	return false
}

func (x *Shop) GetIsIrregularHoliday() bool {
	if x != nil {
		return x.IsIrregularHoliday
	}
	return false
}

func (x *Shop) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Shop) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Shop) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}

func (x *Shop) GetWeekNumber() int32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *Shop) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *Shop) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Shop) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Shop) GetIsHoliday() bool {
	if x != nil {
		return x.IsHoliday
	}
	return false
}

func (x *Shop) GetInCurrentSales() bool {
	if x != nil {
		return x.InCurrentSales
	}
	return false
}

func (x *Shop) GetIsStamped() bool {
	if x != nil {
		return x.IsStamped
	}
	return false
}

func (x *Shop) GetNumberOfTimes() int32 {
	if x != nil {
		return x.NumberOfTimes
	}
	return 0
}

type ShopLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId        int64                  `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopLocation) Reset() {
	*x = ShopLocation{}
	mi := &file_egp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopLocation) ProtoMessage() {}

func (x *ShopLocation) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopLocation.ProtoReflect.Descriptor instead.
func (*ShopLocation) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{7}
}

func (x *ShopLocation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopLocation) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ShopLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ShopLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *ShopLocation) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ShopTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId        int64                  `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	WeekNumber    int32                  `protobuf:"varint,3,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	DayOfWeek     int32                  `protobuf:"varint,4,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	StartTime     string                 `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsHoliday     bool                   `protobuf:"varint,7,opt,name=is_holiday,json=isHoliday,proto3" json:"is_holiday,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopTime) Reset() {
	*x = ShopTime{}
	mi := &file_egp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopTime) ProtoMessage() {}

func (x *ShopTime) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopTime.ProtoReflect.Descriptor instead.
func (*ShopTime) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{8}
}

func (x *ShopTime) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopTime) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ShopTime) GetWeekNumber() int32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *ShopTime) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *ShopTime) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ShopTime) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ShopTime) GetIsHoliday() bool {
	if x != nil {
		return x.IsHoliday
	}
	return false
}

type ShopsTotalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopsTotalRequest) Reset() {
	*x = ShopsTotalRequest{}
	mi := &file_egp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopsTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopsTotalRequest) ProtoMessage() {}

func (x *ShopsTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopsTotalRequest.ProtoReflect.Descriptor instead.
func (*ShopsTotalRequest) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{9}
}

func (x *ShopsTotalRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type ShopsTotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalNum      int64                  `protobuf:"varint,1,opt,name=total_num,json=totalNum,proto3" json:"total_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopsTotalResponse) Reset() {
	*x = ShopsTotalResponse{}
	mi := &file_egp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopsTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopsTotalResponse) ProtoMessage() {}

func (x *ShopsTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopsTotalResponse.ProtoReflect.Descriptor instead.
func (*ShopsTotalResponse) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{10}
}

func (x *ShopsTotalResponse) GetTotalNum() int64 {
	if x != nil {
		return x.TotalNum
	}
	return 0
}

type ShopsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchTypes   []SearchType           `protobuf:"varint,1,rep,packed,name=search_types,json=searchTypes,proto3,enum=egp.SearchType" json:"search_types,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	SortOrder     SortOrderType          `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3,enum=egp.SortOrderType" json:"sort_order,omitempty"`
	Latitude      float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopsRequest) Reset() {
	*x = ShopsRequest{}
	mi := &file_egp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopsRequest) ProtoMessage() {}

func (x *ShopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopsRequest.ProtoReflect.Descriptor instead.
func (*ShopsRequest) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{11}
}

func (x *ShopsRequest) GetSearchTypes() []SearchType {
	if x != nil {
		return x.SearchTypes
	}
	return nil
}

func (x *ShopsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShopsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ShopsRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ShopsRequest) GetSortOrder() SortOrderType {
	if x != nil {
		return x.SortOrder
	}
	return SortOrderType_SORT_ORDER_NO
}

func (x *ShopsRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ShopsRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ShopsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shops         []*Shop                `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopsResponse) Reset() {
	*x = ShopsResponse{}
	mi := &file_egp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopsResponse) ProtoMessage() {}

func (x *ShopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopsResponse.ProtoReflect.Descriptor instead.
func (*ShopsResponse) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{12}
}

func (x *ShopsResponse) GetShops() []*Shop {
	if x != nil {
		return x.Shops
	}
	return nil
}

type ShopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShopId        int64                  `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopRequest) Reset() {
	*x = ShopRequest{}
	mi := &file_egp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopRequest) ProtoMessage() {}

func (x *ShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopRequest.ProtoReflect.Descriptor instead.
func (*ShopRequest) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{13}
}

func (x *ShopRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShopRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type ShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shop          *Shop                  `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	IsEventPeriod bool                   `protobuf:"varint,2,opt,name=is_event_period,json=isEventPeriod,proto3" json:"is_event_period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopResponse) Reset() {
	*x = ShopResponse{}
	mi := &file_egp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopResponse) ProtoMessage() {}

func (x *ShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopResponse.ProtoReflect.Descriptor instead.
func (*ShopResponse) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{14}
}

func (x *ShopResponse) GetShop() *Shop {
	if x != nil {
		return x.Shop
	}
	return nil
}

func (x *ShopResponse) GetIsEventPeriod() bool {
	if x != nil {
		return x.IsEventPeriod
	}
	return false
}

type StampRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShopId        int64                  `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StampRequest) Reset() {
	*x = StampRequest{}
	mi := &file_egp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StampRequest) ProtoMessage() {}

func (x *StampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StampRequest.ProtoReflect.Descriptor instead.
func (*StampRequest) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{15}
}

func (x *StampRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StampRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type StampResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumberOfTimes int32                  `protobuf:"varint,1,opt,name=number_of_times,json=numberOfTimes,proto3" json:"number_of_times,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StampResponse) Reset() {
	*x = StampResponse{}
	mi := &file_egp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StampResponse) ProtoMessage() {}

func (x *StampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StampResponse.ProtoReflect.Descriptor instead.
func (*StampResponse) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{16}
}

func (x *StampResponse) GetNumberOfTimes() int32 {
	if x != nil {
		return x.NumberOfTimes
	}
	return 0
}

type MergeUserStampRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AnonymousUserId string                 `protobuf:"bytes,2,opt,name=anonymous_user_id,json=anonymousUserId,proto3" json:"anonymous_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MergeUserStampRequest) Reset() {
	*x = MergeUserStampRequest{}
	mi := &file_egp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeUserStampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeUserStampRequest) ProtoMessage() {}

func (x *MergeUserStampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeUserStampRequest.ProtoReflect.Descriptor instead.
func (*MergeUserStampRequest) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{17}
}

func (x *MergeUserStampRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MergeUserStampRequest) GetAnonymousUserId() string {
	if x != nil {
		return x.AnonymousUserId
	}
	return ""
}

type MergeUserStampResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StampNum      int32                  `protobuf:"varint,1,opt,name=stamp_num,json=stampNum,proto3" json:"stamp_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeUserStampResponse) Reset() {
	*x = MergeUserStampResponse{}
	mi := &file_egp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeUserStampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeUserStampResponse) ProtoMessage() {}

func (x *MergeUserStampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeUserStampResponse.ProtoReflect.Descriptor instead.
func (*MergeUserStampResponse) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{18}
}

func (x *MergeUserStampResponse) GetStampNum() int32 {
	if x != nil {
		return x.StampNum
	}
	return 0
}

// ユーザー関連メッセージ
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                 // Firebase UID
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                                 // メールアドレス（任意）
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`  // 表示名
	IsAnonymous   bool                   `protobuf:"varint,4,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"` // 匿名ユーザーフラグ
	ProviderId    string                 `protobuf:"bytes,5,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`     // 認証プロバイダー（anonymous, google.com, password等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_egp_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{19}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

func (x *User) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type SyncUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Firebase ID Tokenから取得した情報がInterceptorでContextに設定されるため
	// リクエストボディは空でも可。display_nameのみクライアントから送信可能
	DisplayName   string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // 表示名（任意、クライアントから設定可能）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserRequest) Reset() {
	*x = SyncUserRequest{}
	mi := &file_egp_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserRequest) ProtoMessage() {}

func (x *SyncUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserRequest.ProtoReflect.Descriptor instead.
func (*SyncUserRequest) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{20}
}

func (x *SyncUserRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type SyncUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`                               // 同期されたユーザー情報
	IsNewUser     bool                   `protobuf:"varint,2,opt,name=is_new_user,json=isNewUser,proto3" json:"is_new_user,omitempty"` // 新規作成されたかどうか
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserResponse) Reset() {
	*x = SyncUserResponse{}
	mi := &file_egp_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserResponse) ProtoMessage() {}

func (x *SyncUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserResponse.ProtoReflect.Descriptor instead.
func (*SyncUserResponse) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{21}
}

func (x *SyncUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *SyncUserResponse) GetIsNewUser() bool {
	if x != nil {
		return x.IsNewUser
	}
	return false
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_egp_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{22}
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_egp_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{23}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrevUserId    string                 `protobuf:"bytes,1,opt,name=prev_user_id,json=prevUserId,proto3" json:"prev_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_egp_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateUserRequest) GetPrevUserId() string {
	if x != nil {
		return x.PrevUserId
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_egp_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_egp_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{26}
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_egp_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DefaultYearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultYearRequest) Reset() {
	*x = DefaultYearRequest{}
	mi := &file_egp_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultYearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultYearRequest) ProtoMessage() {}

func (x *DefaultYearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultYearRequest.ProtoReflect.Descriptor instead.
func (*DefaultYearRequest) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{28}
}

type DefaultYearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultYearResponse) Reset() {
	*x = DefaultYearResponse{}
	mi := &file_egp_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultYearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultYearResponse) ProtoMessage() {}

func (x *DefaultYearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultYearResponse.ProtoReflect.Descriptor instead.
func (*DefaultYearResponse) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{29}
}

func (x *DefaultYearResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type YearsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	YearOrder     YearOrder              `protobuf:"varint,1,opt,name=year_order,json=yearOrder,proto3,enum=egp.YearOrder" json:"year_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearsRequest) Reset() {
	*x = YearsRequest{}
	mi := &file_egp_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearsRequest) ProtoMessage() {}

func (x *YearsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearsRequest.ProtoReflect.Descriptor instead.
func (*YearsRequest) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{30}
}

func (x *YearsRequest) GetYearOrder() YearOrder {
	if x != nil {
		return x.YearOrder
	}
	return YearOrder_YEAR_ORDER_ASC
}

type YearsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Years         []int32                `protobuf:"varint,1,rep,packed,name=years,proto3" json:"years,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearsResponse) Reset() {
	*x = YearsResponse{}
	mi := &file_egp_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearsResponse) ProtoMessage() {}

func (x *YearsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egp_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearsResponse.ProtoReflect.Descriptor instead.
func (*YearsResponse) Descriptor() ([]byte, []int) {
	return file_egp_proto_rawDescGZIP(), []int{31}
}

func (x *YearsResponse) GetYears() []int32 {
	if x != nil {
		return x.Years
	}
	return nil
}

var File_egp_proto protoreflect.FileDescriptor

const file_egp_proto_rawDesc = "" +
	"\n" +
	"\tegp.proto\x12\x03egp\"B\n" +
	"\x04Date\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x03 \x01(\x05R\x03day\"\x8f\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12(\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\t.egp.DateR\tstartDate\x12$\n" +
	"\bend_date\x18\x05 \x01(\v2\t.egp.DateR\aendDate\".\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\";\n" +
	"\n" +
	"Categories\x12-\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\r.egp.CategoryR\n" +
	"categories\".\n" +
	"\bBeerType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"9\n" +
	"\tBeerTypes\x12,\n" +
	"\n" +
	"beer_types\x18\x01 \x03(\v2\r.egp.BeerTypeR\tbeerTypes\"\xda\n" +
	"\n" +
	"\x04Shop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04year\x18\" \x01(\x05R\x04year\x122\n" +
	"\vcategory_id\x18\x03 \x01(\x0e2\x11.egp.CategoryTypeR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18# \x01(\tR\fcategoryName\x12\x0e\n" +
	"\x02no\x18\x04 \x01(\x05R\x02no\x12\x1b\n" +
	"\tshop_name\x18\x05 \x01(\tR\bshopName\x12\x1b\n" +
	"\tmenu_name\x18\x06 \x01(\tR\bmenuName\x12$\n" +
	"\x0emenu_image_url\x18$ \x01(\tR\fmenuImageUrl\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12#\n" +
	"\rbusiness_days\x18\t \x01(\tR\fbusinessDays\x12'\n" +
	"\x0fregular_holiday\x18\n" +
	" \x01(\tR\x0eregularHoliday\x12%\n" +
	"\x0ebusiness_hours\x18\v \x01(\tR\rbusinessHours\x12!\n" +
	"\fcharge_price\x18\f \x01(\tR\vchargePrice\x126\n" +
	"\x17normalized_charge_price\x18\r \x01(\x05R\x15normalizedChargePrice\x12!\n" +
	"\fsingle_price\x18\x0e \x01(\tR\vsinglePrice\x126\n" +
	"\x17normalized_single_price\x18\x0f \x01(\x05R\x15normalizedSinglePrice\x12\x1b\n" +
	"\tset_price\x18\x10 \x01(\tR\bsetPrice\x120\n" +
	"\x14normalized_set_price\x18\x11 \x01(\x05R\x12normalizedSetPrice\x12\x1b\n" +
	"\tbeer_type\x18\x12 \x01(\tR\bbeerType\x12+\n" +
	"\x11needs_reservation\x18\x13 \x01(\tR\x10needsReservation\x12@\n" +
	"\x1cnormalized_needs_reservation\x18\x14 \x01(\bR\x1anormalizedNeedsReservation\x12!\n" +
	"\fuse_hachipay\x18\x15 \x01(\tR\vuseHachipay\x126\n" +
	"\x17normalized_use_hachipay\x18\x16 \x01(\bR\x15normalizedUseHachipay\x12&\n" +
	"\x0fis_open_holiday\x18\x17 \x01(\bR\risOpenHoliday\x120\n" +
	"\x14is_irregular_holiday\x18\x18 \x01(\bR\x12isIrregularHoliday\x12\x1a\n" +
	"\blatitude\x18\x19 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x1a \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bdistance\x18\x1b \x01(\tR\bdistance\x12\x1f\n" +
	"\vweek_number\x18\x1c \x01(\x05R\n" +
	"weekNumber\x12\x1e\n" +
	"\vday_of_week\x18\x1d \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x1e \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x1f \x01(\tR\aendTime\x12\x1d\n" +
	"\n" +
	"is_holiday\x18  \x01(\bR\tisHoliday\x12(\n" +
	"\x10in_current_sales\x18! \x01(\bR\x0einCurrentSales\x12\x1d\n" +
	"\n" +
	"is_stamped\x18% \x01(\bR\tisStamped\x12&\n" +
	"\x0fnumber_of_times\x18& \x01(\x05R\rnumberOfTimes\"\x8d\x01\n" +
	"\fShopLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\x03R\x06shopId\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\"\xcd\x01\n" +
	"\bShopTime\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\x03R\x06shopId\x12\x1f\n" +
	"\vweek_number\x18\x03 \x01(\x05R\n" +
	"weekNumber\x12\x1e\n" +
	"\vday_of_week\x18\x04 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\x12\x1d\n" +
	"\n" +
	"is_holiday\x18\a \x01(\bR\tisHoliday\"'\n" +
	"\x11ShopsTotalRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"1\n" +
	"\x12ShopsTotalResponse\x12\x1b\n" +
	"\ttotal_num\x18\x01 \x01(\x03R\btotalNum\"\xf6\x01\n" +
	"\fShopsRequest\x122\n" +
	"\fsearch_types\x18\x01 \x03(\x0e2\x0f.egp.SearchTypeR\vsearchTypes\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x121\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x0e2\x12.egp.SortOrderTypeR\tsortOrder\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\"0\n" +
	"\rShopsResponse\x12\x1f\n" +
	"\x05shops\x18\x01 \x03(\v2\t.egp.ShopR\x05shops\"?\n" +
	"\vShopRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\x03R\x06shopId\"U\n" +
	"\fShopResponse\x12\x1d\n" +
	"\x04shop\x18\x01 \x01(\v2\t.egp.ShopR\x04shop\x12&\n" +
	"\x0fis_event_period\x18\x02 \x01(\bR\risEventPeriod\"@\n" +
	"\fStampRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\x03R\x06shopId\"7\n" +
	"\rStampResponse\x12&\n" +
	"\x0fnumber_of_times\x18\x01 \x01(\x05R\rnumberOfTimes\"\\\n" +
	"\x15MergeUserStampRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x11anonymous_user_id\x18\x02 \x01(\tR\x0fanonymousUserId\"5\n" +
	"\x16MergeUserStampResponse\x12\x1b\n" +
	"\tstamp_num\x18\x01 \x01(\x05R\bstampNum\"\x9c\x01\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12!\n" +
	"\fis_anonymous\x18\x04 \x01(\bR\visAnonymous\x12\x1f\n" +
	"\vprovider_id\x18\x05 \x01(\tR\n" +
	"providerId\"4\n" +
	"\x0fSyncUserRequest\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\"Q\n" +
	"\x10SyncUserResponse\x12\x1d\n" +
	"\x04user\x18\x01 \x01(\v2\t.egp.UserR\x04user\x12\x1e\n" +
	"\vis_new_user\x18\x02 \x01(\bR\tisNewUser\"\x10\n" +
	"\x0eGetUserRequest\"0\n" +
	"\x0fGetUserResponse\x12\x1d\n" +
	"\x04user\x18\x01 \x01(\v2\t.egp.UserR\x04user\"5\n" +
	"\x11UpdateUserRequest\x12 \n" +
	"\fprev_user_id\x18\x01 \x01(\tR\n" +
	"prevUserId\"3\n" +
	"\x12UpdateUserResponse\x12\x1d\n" +
	"\x04user\x18\x01 \x01(\v2\t.egp.UserR\x04user\"\x13\n" +
	"\x11DeleteUserRequest\"-\n" +
	"\x12DeleteUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x14\n" +
	"\x12DefaultYearRequest\")\n" +
	"\x13DefaultYearResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"=\n" +
	"\fYearsRequest\x12-\n" +
	"\n" +
	"year_order\x18\x01 \x01(\x0e2\x0e.egp.YearOrderR\tyearOrder\"%\n" +
	"\rYearsResponse\x12\x14\n" +
	"\x05years\x18\x01 \x03(\x05R\x05years*\xba\x01\n" +
	"\fCategoryType\x12\x16\n" +
	"\x12CATEGORY_TYPE_NONE\x10\x00\x12\x19\n" +
	"\x15CATEGORY_TYPE_EBISU_1\x10\x01\x12\x19\n" +
	"\x15CATEGORY_TYPE_EBISU_2\x10\x02\x12\x1c\n" +
	"\x18CATEGORY_TYPE_EBISU_WEST\x10\x03\x12\x1d\n" +
	"\x19CATEGORY_TYPE_EBISU_SOUTH\x10\x04\x12\x1f\n" +
	"\x1bCATEGORY_TYPE_BEER_COCKTAIL\x10\x05*\xac\x01\n" +
	"\n" +
	"SearchType\x12 \n" +
	"\x1cSEARCH_TYPE_IN_CURRENT_SALES\x10\x00\x12\x17\n" +
	"\x13SEARCH_TYPE_NOT_YET\x10\x01\x12!\n" +
	"\x1dSEARCH_TYPE_IRREGULAR_HOLIDAY\x10\x02\x12!\n" +
	"\x1dSEARCH_TYPE_NEEDS_RESERVATION\x10\x03\x12\x1d\n" +
	"\x19SEARCH_TYPE_BEER_COCKTAIL\x10\x04*;\n" +
	"\rSortOrderType\x12\x11\n" +
	"\rSORT_ORDER_NO\x10\x00\x12\x17\n" +
	"\x13SORT_ORDER_DISTANCE\x10\x01*4\n" +
	"\tYearOrder\x12\x12\n" +
	"\x0eYEAR_ORDER_ASC\x10\x00\x12\x13\n" +
	"\x0fYEAR_ORDER_DESC\x10\x012\xca\x05\n" +
	"\n" +
	"EgpService\x12@\n" +
	"\rGetShopsTotal\x12\x16.egp.ShopsTotalRequest\x1a\x17.egp.ShopsTotalResponse\x121\n" +
	"\bGetShops\x12\x11.egp.ShopsRequest\x1a\x12.egp.ShopsResponse\x12.\n" +
	"\aGetShop\x12\x10.egp.ShopRequest\x1a\x11.egp.ShopResponse\x121\n" +
	"\bAddStamp\x12\x11.egp.StampRequest\x1a\x12.egp.StampResponse\x124\n" +
	"\vDeleteStamp\x12\x11.egp.StampRequest\x1a\x12.egp.StampResponse\x12I\n" +
	"\x0eMergeUserStamp\x12\x1a.egp.MergeUserStampRequest\x1a\x1b.egp.MergeUserStampResponse\x127\n" +
	"\bSyncUser\x12\x14.egp.SyncUserRequest\x1a\x15.egp.SyncUserResponse\x124\n" +
	"\aGetUser\x12\x13.egp.GetUserRequest\x1a\x14.egp.GetUserResponse\x12=\n" +
	"\n" +
	"UpdateUser\x12\x16.egp.UpdateUserRequest\x1a\x17.egp.UpdateUserResponse\x12=\n" +
	"\n" +
	"DeleteUser\x12\x16.egp.DeleteUserRequest\x1a\x17.egp.DeleteUserResponse\x12C\n" +
	"\x0eGetDefaultYear\x12\x17.egp.DefaultYearRequest\x1a\x18.egp.DefaultYearResponse\x121\n" +
	"\bGetYears\x12\x11.egp.YearsRequest\x1a\x12.egp.YearsResponseB\"Z github.com/go-to/egp_protobuf/pbb\x06proto3"

var (
	file_egp_proto_rawDescOnce sync.Once
	file_egp_proto_rawDescData []byte
)

func file_egp_proto_rawDescGZIP() []byte {
	file_egp_proto_rawDescOnce.Do(func() {
		file_egp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_egp_proto_rawDesc), len(file_egp_proto_rawDesc)))
	})
	return file_egp_proto_rawDescData
}

var file_egp_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_egp_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_egp_proto_goTypes = []any{
	(CategoryType)(0),              // 0: egp.CategoryType
	(SearchType)(0),                // 1: egp.SearchType
	(SortOrderType)(0),             // 2: egp.SortOrderType
	(YearOrder)(0),                 // 3: egp.YearOrder
	(*Date)(nil),                   // 4: egp.Date
	(*Event)(nil),                  // 5: egp.Event
	(*Category)(nil),               // 6: egp.Category
	(*Categories)(nil),             // 7: egp.Categories
	(*BeerType)(nil),               // 8: egp.BeerType
	(*BeerTypes)(nil),              // 9: egp.BeerTypes
	(*Shop)(nil),                   // 10: egp.Shop
	(*ShopLocation)(nil),           // 11: egp.ShopLocation
	(*ShopTime)(nil),               // 12: egp.ShopTime
	(*ShopsTotalRequest)(nil),      // 13: egp.ShopsTotalRequest
	(*ShopsTotalResponse)(nil),     // 14: egp.ShopsTotalResponse
	(*ShopsRequest)(nil),           // 15: egp.ShopsRequest
	(*ShopsResponse)(nil),          // 16: egp.ShopsResponse
	(*ShopRequest)(nil),            // 17: egp.ShopRequest
	(*ShopResponse)(nil),           // 18: egp.ShopResponse
	(*StampRequest)(nil),           // 19: egp.StampRequest
	(*StampResponse)(nil),          // 20: egp.StampResponse
	(*MergeUserStampRequest)(nil),  // 21: egp.MergeUserStampRequest
	(*MergeUserStampResponse)(nil), // 22: egp.MergeUserStampResponse
	(*User)(nil),                   // 23: egp.User
	(*SyncUserRequest)(nil),        // 24: egp.SyncUserRequest
	(*SyncUserResponse)(nil),       // 25: egp.SyncUserResponse
	(*GetUserRequest)(nil),         // 26: egp.GetUserRequest
	(*GetUserResponse)(nil),        // 27: egp.GetUserResponse
	(*UpdateUserRequest)(nil),      // 28: egp.UpdateUserRequest
	(*UpdateUserResponse)(nil),     // 29: egp.UpdateUserResponse
	(*DeleteUserRequest)(nil),      // 30: egp.DeleteUserRequest
	(*DeleteUserResponse)(nil),     // 31: egp.DeleteUserResponse
	(*DefaultYearRequest)(nil),     // 32: egp.DefaultYearRequest
	(*DefaultYearResponse)(nil),    // 33: egp.DefaultYearResponse
	(*YearsRequest)(nil),           // 34: egp.YearsRequest
	(*YearsResponse)(nil),          // 35: egp.YearsResponse
}
var file_egp_proto_depIdxs = []int32{
	4,  // 0: egp.Event.start_date:type_name -> egp.Date
	4,  // 1: egp.Event.end_date:type_name -> egp.Date
	6,  // 2: egp.Categories.categories:type_name -> egp.Category
	8,  // 3: egp.BeerTypes.beer_types:type_name -> egp.BeerType
	0,  // 4: egp.Shop.category_id:type_name -> egp.CategoryType
	1,  // 5: egp.ShopsRequest.search_types:type_name -> egp.SearchType
	2,  // 6: egp.ShopsRequest.sort_order:type_name -> egp.SortOrderType
	10, // 7: egp.ShopsResponse.shops:type_name -> egp.Shop
	10, // 8: egp.ShopResponse.shop:type_name -> egp.Shop
	23, // 9: egp.SyncUserResponse.user:type_name -> egp.User
	23, // 10: egp.GetUserResponse.user:type_name -> egp.User
	23, // 11: egp.UpdateUserResponse.user:type_name -> egp.User
	3,  // 12: egp.YearsRequest.year_order:type_name -> egp.YearOrder
	13, // 13: egp.EgpService.GetShopsTotal:input_type -> egp.ShopsTotalRequest
	15, // 14: egp.EgpService.GetShops:input_type -> egp.ShopsRequest
	17, // 15: egp.EgpService.GetShop:input_type -> egp.ShopRequest
	19, // 16: egp.EgpService.AddStamp:input_type -> egp.StampRequest
	19, // 17: egp.EgpService.DeleteStamp:input_type -> egp.StampRequest
	21, // 18: egp.EgpService.MergeUserStamp:input_type -> egp.MergeUserStampRequest
	24, // 19: egp.EgpService.SyncUser:input_type -> egp.SyncUserRequest
	26, // 20: egp.EgpService.GetUser:input_type -> egp.GetUserRequest
	28, // 21: egp.EgpService.UpdateUser:input_type -> egp.UpdateUserRequest
	30, // 22: egp.EgpService.DeleteUser:input_type -> egp.DeleteUserRequest
	32, // 23: egp.EgpService.GetDefaultYear:input_type -> egp.DefaultYearRequest
	34, // 24: egp.EgpService.GetYears:input_type -> egp.YearsRequest
	14, // 25: egp.EgpService.GetShopsTotal:output_type -> egp.ShopsTotalResponse
	16, // 26: egp.EgpService.GetShops:output_type -> egp.ShopsResponse
	18, // 27: egp.EgpService.GetShop:output_type -> egp.ShopResponse
	20, // 28: egp.EgpService.AddStamp:output_type -> egp.StampResponse
	20, // 29: egp.EgpService.DeleteStamp:output_type -> egp.StampResponse
	22, // 30: egp.EgpService.MergeUserStamp:output_type -> egp.MergeUserStampResponse
	25, // 31: egp.EgpService.SyncUser:output_type -> egp.SyncUserResponse
	27, // 32: egp.EgpService.GetUser:output_type -> egp.GetUserResponse
	29, // 33: egp.EgpService.UpdateUser:output_type -> egp.UpdateUserResponse
	31, // 34: egp.EgpService.DeleteUser:output_type -> egp.DeleteUserResponse
	33, // 35: egp.EgpService.GetDefaultYear:output_type -> egp.DefaultYearResponse
	35, // 36: egp.EgpService.GetYears:output_type -> egp.YearsResponse
	25, // [25:37] is the sub-list for method output_type
	13, // [13:25] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_egp_proto_init() }
func file_egp_proto_init() {
	if File_egp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_egp_proto_rawDesc), len(file_egp_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_egp_proto_goTypes,
		DependencyIndexes: file_egp_proto_depIdxs,
		EnumInfos:         file_egp_proto_enumTypes,
		MessageInfos:      file_egp_proto_msgTypes,
	}.Build()
	File_egp_proto = out.File
	file_egp_proto_goTypes = nil
	file_egp_proto_depIdxs = nil
}
