// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: egp.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EgpService_GetShopsTotal_FullMethodName         = "/egp.EgpService/GetShopsTotal"
	EgpService_GetShops_FullMethodName              = "/egp.EgpService/GetShops"
	EgpService_GetShop_FullMethodName               = "/egp.EgpService/GetShop"
	EgpService_AddStamp_FullMethodName              = "/egp.EgpService/AddStamp"
	EgpService_DeleteStamp_FullMethodName           = "/egp.EgpService/DeleteStamp"
	EgpService_MergeUserStamp_FullMethodName        = "/egp.EgpService/MergeUserStamp"
	EgpService_SyncUser_FullMethodName              = "/egp.EgpService/SyncUser"
	EgpService_GetUser_FullMethodName               = "/egp.EgpService/GetUser"
	EgpService_UpdateUser_FullMethodName            = "/egp.EgpService/UpdateUser"
	EgpService_DeleteUser_FullMethodName            = "/egp.EgpService/DeleteUser"
	EgpService_GetDefaultYear_FullMethodName        = "/egp.EgpService/GetDefaultYear"
	EgpService_GetYears_FullMethodName              = "/egp.EgpService/GetYears"
	EgpService_RegisterFcmToken_FullMethodName      = "/egp.EgpService/RegisterFcmToken"
	EgpService_SendVerificationEmail_FullMethodName = "/egp.EgpService/SendVerificationEmail"
)

// EgpServiceClient is the client API for EgpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EgpServiceClient interface {
	// 店舗総数取得
	GetShopsTotal(ctx context.Context, in *ShopsTotalRequest, opts ...grpc.CallOption) (*ShopsTotalResponse, error)
	// 店舗情報取得
	GetShops(ctx context.Context, in *ShopsRequest, opts ...grpc.CallOption) (*ShopsResponse, error)
	// 店舗情報取得
	GetShop(ctx context.Context, in *ShopRequest, opts ...grpc.CallOption) (*ShopResponse, error)
	// スタンプ追加
	AddStamp(ctx context.Context, in *StampRequest, opts ...grpc.CallOption) (*StampResponse, error)
	// スタンプ削除
	DeleteStamp(ctx context.Context, in *StampRequest, opts ...grpc.CallOption) (*StampResponse, error)
	// ユーザースタンプマージ（匿名→永続化ユーザー移行時）
	MergeUserStamp(ctx context.Context, in *MergeUserStampRequest, opts ...grpc.CallOption) (*MergeUserStampResponse, error)
	// ユーザー同期（Firebase認証後にバックエンドDBと同期）
	SyncUser(ctx context.Context, in *SyncUserRequest, opts ...grpc.CallOption) (*SyncUserResponse, error)
	// ユーザー情報取得
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	// ユーザー情報更新
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	// ユーザー情報削除
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	// デフォルトの年取得
	GetDefaultYear(ctx context.Context, in *DefaultYearRequest, opts ...grpc.CallOption) (*DefaultYearResponse, error)
	// 年一覧取得
	GetYears(ctx context.Context, in *YearsRequest, opts ...grpc.CallOption) (*YearsResponse, error)
	// FCMトークン登録
	RegisterFcmToken(ctx context.Context, in *RegisterFcmTokenRequest, opts ...grpc.CallOption) (*RegisterFcmTokenResponse, error)
	// メール確認メール送信
	SendVerificationEmail(ctx context.Context, in *SendVerificationEmailRequest, opts ...grpc.CallOption) (*SendVerificationEmailResponse, error)
}

type egpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEgpServiceClient(cc grpc.ClientConnInterface) EgpServiceClient {
	return &egpServiceClient{cc}
}

func (c *egpServiceClient) GetShopsTotal(ctx context.Context, in *ShopsTotalRequest, opts ...grpc.CallOption) (*ShopsTotalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopsTotalResponse)
	err := c.cc.Invoke(ctx, EgpService_GetShopsTotal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egpServiceClient) GetShops(ctx context.Context, in *ShopsRequest, opts ...grpc.CallOption) (*ShopsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopsResponse)
	err := c.cc.Invoke(ctx, EgpService_GetShops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egpServiceClient) GetShop(ctx context.Context, in *ShopRequest, opts ...grpc.CallOption) (*ShopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopResponse)
	err := c.cc.Invoke(ctx, EgpService_GetShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egpServiceClient) AddStamp(ctx context.Context, in *StampRequest, opts ...grpc.CallOption) (*StampResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StampResponse)
	err := c.cc.Invoke(ctx, EgpService_AddStamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egpServiceClient) DeleteStamp(ctx context.Context, in *StampRequest, opts ...grpc.CallOption) (*StampResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StampResponse)
	err := c.cc.Invoke(ctx, EgpService_DeleteStamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egpServiceClient) MergeUserStamp(ctx context.Context, in *MergeUserStampRequest, opts ...grpc.CallOption) (*MergeUserStampResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeUserStampResponse)
	err := c.cc.Invoke(ctx, EgpService_MergeUserStamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egpServiceClient) SyncUser(ctx context.Context, in *SyncUserRequest, opts ...grpc.CallOption) (*SyncUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncUserResponse)
	err := c.cc.Invoke(ctx, EgpService_SyncUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egpServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, EgpService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egpServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, EgpService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egpServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, EgpService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egpServiceClient) GetDefaultYear(ctx context.Context, in *DefaultYearRequest, opts ...grpc.CallOption) (*DefaultYearResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefaultYearResponse)
	err := c.cc.Invoke(ctx, EgpService_GetDefaultYear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egpServiceClient) GetYears(ctx context.Context, in *YearsRequest, opts ...grpc.CallOption) (*YearsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearsResponse)
	err := c.cc.Invoke(ctx, EgpService_GetYears_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egpServiceClient) RegisterFcmToken(ctx context.Context, in *RegisterFcmTokenRequest, opts ...grpc.CallOption) (*RegisterFcmTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterFcmTokenResponse)
	err := c.cc.Invoke(ctx, EgpService_RegisterFcmToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egpServiceClient) SendVerificationEmail(ctx context.Context, in *SendVerificationEmailRequest, opts ...grpc.CallOption) (*SendVerificationEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendVerificationEmailResponse)
	err := c.cc.Invoke(ctx, EgpService_SendVerificationEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EgpServiceServer is the server API for EgpService service.
// All implementations must embed UnimplementedEgpServiceServer
// for forward compatibility.
type EgpServiceServer interface {
	// 店舗総数取得
	GetShopsTotal(context.Context, *ShopsTotalRequest) (*ShopsTotalResponse, error)
	// 店舗情報取得
	GetShops(context.Context, *ShopsRequest) (*ShopsResponse, error)
	// 店舗情報取得
	GetShop(context.Context, *ShopRequest) (*ShopResponse, error)
	// スタンプ追加
	AddStamp(context.Context, *StampRequest) (*StampResponse, error)
	// スタンプ削除
	DeleteStamp(context.Context, *StampRequest) (*StampResponse, error)
	// ユーザースタンプマージ（匿名→永続化ユーザー移行時）
	MergeUserStamp(context.Context, *MergeUserStampRequest) (*MergeUserStampResponse, error)
	// ユーザー同期（Firebase認証後にバックエンドDBと同期）
	SyncUser(context.Context, *SyncUserRequest) (*SyncUserResponse, error)
	// ユーザー情報取得
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	// ユーザー情報更新
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	// ユーザー情報削除
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	// デフォルトの年取得
	GetDefaultYear(context.Context, *DefaultYearRequest) (*DefaultYearResponse, error)
	// 年一覧取得
	GetYears(context.Context, *YearsRequest) (*YearsResponse, error)
	// FCMトークン登録
	RegisterFcmToken(context.Context, *RegisterFcmTokenRequest) (*RegisterFcmTokenResponse, error)
	// メール確認メール送信
	SendVerificationEmail(context.Context, *SendVerificationEmailRequest) (*SendVerificationEmailResponse, error)
	mustEmbedUnimplementedEgpServiceServer()
}

// UnimplementedEgpServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEgpServiceServer struct{}

func (UnimplementedEgpServiceServer) GetShopsTotal(context.Context, *ShopsTotalRequest) (*ShopsTotalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShopsTotal not implemented")
}
func (UnimplementedEgpServiceServer) GetShops(context.Context, *ShopsRequest) (*ShopsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShops not implemented")
}
func (UnimplementedEgpServiceServer) GetShop(context.Context, *ShopRequest) (*ShopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShop not implemented")
}
func (UnimplementedEgpServiceServer) AddStamp(context.Context, *StampRequest) (*StampResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddStamp not implemented")
}
func (UnimplementedEgpServiceServer) DeleteStamp(context.Context, *StampRequest) (*StampResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStamp not implemented")
}
func (UnimplementedEgpServiceServer) MergeUserStamp(context.Context, *MergeUserStampRequest) (*MergeUserStampResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MergeUserStamp not implemented")
}
func (UnimplementedEgpServiceServer) SyncUser(context.Context, *SyncUserRequest) (*SyncUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncUser not implemented")
}
func (UnimplementedEgpServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedEgpServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedEgpServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedEgpServiceServer) GetDefaultYear(context.Context, *DefaultYearRequest) (*DefaultYearResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDefaultYear not implemented")
}
func (UnimplementedEgpServiceServer) GetYears(context.Context, *YearsRequest) (*YearsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetYears not implemented")
}
func (UnimplementedEgpServiceServer) RegisterFcmToken(context.Context, *RegisterFcmTokenRequest) (*RegisterFcmTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterFcmToken not implemented")
}
func (UnimplementedEgpServiceServer) SendVerificationEmail(context.Context, *SendVerificationEmailRequest) (*SendVerificationEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendVerificationEmail not implemented")
}
func (UnimplementedEgpServiceServer) mustEmbedUnimplementedEgpServiceServer() {}
func (UnimplementedEgpServiceServer) testEmbeddedByValue()                    {}

// UnsafeEgpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EgpServiceServer will
// result in compilation errors.
type UnsafeEgpServiceServer interface {
	mustEmbedUnimplementedEgpServiceServer()
}

func RegisterEgpServiceServer(s grpc.ServiceRegistrar, srv EgpServiceServer) {
	// If the following call panics, it indicates UnimplementedEgpServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EgpService_ServiceDesc, srv)
}

func _EgpService_GetShopsTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopsTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgpServiceServer).GetShopsTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgpService_GetShopsTotal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgpServiceServer).GetShopsTotal(ctx, req.(*ShopsTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgpService_GetShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgpServiceServer).GetShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgpService_GetShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgpServiceServer).GetShops(ctx, req.(*ShopsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgpService_GetShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgpServiceServer).GetShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgpService_GetShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgpServiceServer).GetShop(ctx, req.(*ShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgpService_AddStamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgpServiceServer).AddStamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgpService_AddStamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgpServiceServer).AddStamp(ctx, req.(*StampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgpService_DeleteStamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgpServiceServer).DeleteStamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgpService_DeleteStamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgpServiceServer).DeleteStamp(ctx, req.(*StampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgpService_MergeUserStamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeUserStampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgpServiceServer).MergeUserStamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgpService_MergeUserStamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgpServiceServer).MergeUserStamp(ctx, req.(*MergeUserStampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgpService_SyncUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgpServiceServer).SyncUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgpService_SyncUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgpServiceServer).SyncUser(ctx, req.(*SyncUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgpService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgpServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgpService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgpServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgpService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgpServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgpService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgpServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgpService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgpServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgpService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgpServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgpService_GetDefaultYear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultYearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgpServiceServer).GetDefaultYear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgpService_GetDefaultYear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgpServiceServer).GetDefaultYear(ctx, req.(*DefaultYearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgpService_GetYears_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgpServiceServer).GetYears(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgpService_GetYears_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgpServiceServer).GetYears(ctx, req.(*YearsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgpService_RegisterFcmToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterFcmTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgpServiceServer).RegisterFcmToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgpService_RegisterFcmToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgpServiceServer).RegisterFcmToken(ctx, req.(*RegisterFcmTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgpService_SendVerificationEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendVerificationEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgpServiceServer).SendVerificationEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgpService_SendVerificationEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgpServiceServer).SendVerificationEmail(ctx, req.(*SendVerificationEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EgpService_ServiceDesc is the grpc.ServiceDesc for EgpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EgpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "egp.EgpService",
	HandlerType: (*EgpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShopsTotal",
			Handler:    _EgpService_GetShopsTotal_Handler,
		},
		{
			MethodName: "GetShops",
			Handler:    _EgpService_GetShops_Handler,
		},
		{
			MethodName: "GetShop",
			Handler:    _EgpService_GetShop_Handler,
		},
		{
			MethodName: "AddStamp",
			Handler:    _EgpService_AddStamp_Handler,
		},
		{
			MethodName: "DeleteStamp",
			Handler:    _EgpService_DeleteStamp_Handler,
		},
		{
			MethodName: "MergeUserStamp",
			Handler:    _EgpService_MergeUserStamp_Handler,
		},
		{
			MethodName: "SyncUser",
			Handler:    _EgpService_SyncUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _EgpService_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _EgpService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _EgpService_DeleteUser_Handler,
		},
		{
			MethodName: "GetDefaultYear",
			Handler:    _EgpService_GetDefaultYear_Handler,
		},
		{
			MethodName: "GetYears",
			Handler:    _EgpService_GetYears_Handler,
		},
		{
			MethodName: "RegisterFcmToken",
			Handler:    _EgpService_RegisterFcmToken_Handler,
		},
		{
			MethodName: "SendVerificationEmail",
			Handler:    _EgpService_SendVerificationEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "egp.proto",
}
